# frozen_string_literal: true

source "https://rubygems.org"

# Local-only Gems
#install_if -> { ENV["GITHUB_ACTIONS"] != "true" } do
    gem "webrick", "~> 1.9"
#end

# gems for local and GitHub Pages
gem "github-pages", "~> 232", :group => :jekyll_plugins
gem "jekyll-autoprefixer", "~> 1.0", :group => :jekyll_plugins
gem "execjs", "= 2.7"